name: Auto Merge
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: 'automerge'
          MERGE_METHOD: squash
          DELETE_BRANCH: true
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000

